# -*- coding: utf-8 -*-
"""SteamindirimAvcisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyEhI6LIH7xH56hugC4yGdDuhI2S8W5z
"""

import requests
from bs4 import BeautifulSoup
import time
from datetime import datetime

# --- AYARLAR ---
TELEGRAM_TOKEN = "Buraya Token gelecek"
CHAT_ID = "Buraya hangi kişiye yada gruba botu çalıştıracaksanız onun ID si gelecek" # Örn: "-10012345678" (Tırnak içinde)

# --- HAFIZA ---
# Botun oyunları hatırlaması için boş bir sözlük
# Format: { 'APP_ID': İndirim_Oranı } -> { '2195250': 50 }
hafiza = {}

def telegrama_gonder(mesaj):
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        payload = {"chat_id": CHAT_ID, "text": mesaj, "parse_mode": "HTML"}
        requests.post(url, json=payload)
    except:
        pass # Hata olursa bot durmasın

def botu_calistir():
    print(f"🤖 Bot Başlatıldı! {datetime.now().strftime('%H:%M:%S')}")
    print("Mevcut indirimleri hafızaya alıyor, sadece değişiklikleri bildirecek...\n")

    while True: # SONSUZ DÖNGÜ
        try:
            # 1. Steam Top Listesini Çek
            url = "https://store.steampowered.com/search/?filter=topsellers&cc=tr&l=turkish"
            headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
            cookies = {'birthtime': '568028401', 'lastagecheckage': '1-0-1990', 'wants_mature_content': '1'}

            response = requests.get(url, headers=headers, cookies=cookies)
            soup = BeautifulSoup(response.content, 'html.parser')
            oyunlar = soup.select('#search_resultsRows > a')[:40] # İlk 40 oyuna bak

            # Bu turda gördüğümüz oyunları not alalım
            bu_tur_gorulenler = []

            for oyun in oyunlar:
                app_id = oyun.get('data-ds-appid')
                if not app_id or ',' in app_id: continue

                # API Kontrolü
                api_url = f"https://store.steampowered.com/api/appdetails?appids={app_id}&cc=tr&filters=price_overview,basic"
                try:
                    res = requests.get(api_url).json()
                except:
                    continue # API hatası varsa geç

                if res and str(app_id) in res and res[str(app_id)]["success"]:
                    data = res[str(app_id)]["data"]

                    if data.get("is_free") == True: continue
                    if not data.get("price_overview"): continue

                    isim = data["name"]
                    fiyat_data = data["price_overview"]
                    yeni_indirim = fiyat_data['discount_percent']

                    # Bu oyunu gördüğümüzü not et
                    bu_tur_gorulenler.append(app_id)

                    # --- HAFIZA KONTROLÜ (EN ÖNEMLİ KISIM) ---
                    eski_indirim = hafiza.get(app_id, 0) # Hafızada yoksa 0 kabul et

                    # SENARYO 1: YENİ İNDİRİM BAŞLADI (Eskiden 0'dı, şimdi > 0)
                    if eski_indirim == 0 and yeni_indirim > 0:
                        final = fiyat_data['final'] / 100
                        ilk = fiyat_data['initial'] / 100
                        kazanc = ilk - final

                        mesaj = (
                            f"🚨 <b>YENİ İNDİRİM BAŞLADI!</b>\n\n"
                            f"🎮 <b>{isim}</b>\n"
                            f"🔥 İndirim: <b>%{yeni_indirim}</b>\n"
                            f"💰 Fiyat: {final} {fiyat_data['currency']}\n"
                            f"📉 Eski: {ilk}\n"
                            f"🔗 <a href='https://store.steampowered.com/app/{app_id}'>İncele</a>"
                        )
                        telegrama_gonder(mesaj)
                        print(f"🔔 Yeni İndirim Bildirildi: {isim}")

                    # SENARYO 2: İNDİRİM ORANI ARTTI (Eskiden %20, şimdi %50)
                    elif yeni_indirim > eski_indirim:
                        mesaj = (
                            f"🔥 <b>İNDİRİM YÜKSELDİ!</b>\n"
                            f"🎮 {isim}: %{eski_indirim} -> <b>%{yeni_indirim}</b> oldu!"
                        )
                        telegrama_gonder(mesaj)

                    # SENARYO 3: İNDİRİM BİTTİ (Eskiden indirimdeydi, şimdi 0)
                    # Bunu döngü dışında kontrol edeceğiz ama burada notunu güncelleyelim.

                    # Hafızayı Güncelle
                    hafiza[app_id] = yeni_indirim

                # API ban yememek için minik bekleme
                time.sleep(0.5)

            # --- İNDİRİMİ BİTENLERİ KONTROL ET ---
            # Hafızada olup, bu turda artık indirimde olmayanları bulabiliriz
            # (Basitlik olsun diye şimdilik sadece yeni indirimleri ekledim,
            # indirim bitti mesajı bazen can sıkıcı olabilir, istersen ekleriz)

            print(f"✅ Kontrol tamamlandı. 60 saniye bekleniyor... ({datetime.now().strftime('%H:%M')})")
            time.sleep(60) # 1 Dakika uyu

        except Exception as e:
            print(f"⚠️ Bir hata oldu, 10 saniye sonra tekrar denenecek: {e}")
            time.sleep(10)

if __name__ == "__main__":
    botu_calistir()